Models/ErrorViewModel.cs
namespace AvaliacaoLP3_3BIM.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ViewModels/LojasViewModel.cs
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLP3_3BIM.Models;
using System.Diagnostics;
using AvaliacaoLP3_3BIM.Controllers;

namespace AvaliacaoLP3_3BIM.ViewModels;

public class LojasViewModel {

    public int Id { get; set; }
    public string Piso { get; set; }
    public string Nome { get; set; }
    public string Descricao { get; set; }
    public string TipoLoja { get; set; }
    public string Email { get; set; }

    public LojasViewModel(int id, string piso, string nome, string descricao, string tipoLoja, string email)
    {
        Id = id;
        Piso = piso;
        Nome = nome;
        Descricao = descricao;
        TipoLoja = tipoLoja;
        Email = email;
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLP3_3BIM.Models;

namespace AvaliacaoLP3_3BIM.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LojasController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AvaliacaoLP3_3BIM.ViewModels;
using AvaliacaoLP3_3BIM.Models;

namespace AvaliacaoLP3_3BIM.Controllers;

public class LojasController : Controller
{
    //private static List<LojasViewModel> lojas = new List<LojasViewModel>{
        //new LojasViewModel(32, "Piso 3", "Tênis Brasil", "Aqui tem tênis", "Loja", "tenis@email.com"),
        //new LojasViewModel(33, "Piso 3", "Lembranças já", "Lembranças uhul", "Kiosque", "lemb@email.com"),
        //new LojasViewModel(12, "Piso 1", "Sorvetinho Gelado", "Sorvetes não quentes", "Kiosque", "sorvet@email.com"),
        //new LojasViewModel(24, "Piso 2", "Saraivada", "Uma tempestade de livros", "Loja", "livros@email.com"),
        //new LojasViewModel(29, "Piso 2", "Mitsue lanches", "Cantina do IFSP no shopping!!!", "Kiosque", "lanche@email.com"),
    //};

    public static List<LojasViewModel> lojas = new List<LojasViewModel>();

    public IActionResult Loja()
    {
        return View(lojas);
    }

    public IActionResult Detalhes([FromForm] int id)
    {
        return View(lojas[id]);
    }

    public IActionResult CadastrarLoja()
    {
        return View();
    }

    public IActionResult ValidarId()
    {
        return View();
    }

    public IActionResult ValidarCadastro([FromForm] int id, [FromForm] string piso, [FromForm] string nome, [FromForm] string descricao, [FromForm] string tipoLoja, [FromForm] string email )
    {

        foreach(var loja in lojas)
        {
            if(nome == loja.Nome){
                ViewData["Nome"] = nome;
                return View();
            }
            else if(id == loja.Id){
                return View("ValidarId");
            }
        } 

        LojasViewModel comercio = new LojasViewModel(id, piso, nome, descricao, tipoLoja, email);
        lojas.Add(comercio);
        return View("CadastrarLoja");
    }

    public IActionResult Administracao()
    {
        return View();
    }

    public IActionResult Deletar(int id){
        if(lojas.Count() == 1){
            lojas.Clear();
        }else
            lojas.RemoveAt(id);

        foreach (var loja in lojas)
        {
            loja.Id = lojas.IndexOf(loja);
        }
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lojas/Administracao.cshtml
@model List<AvaliacaoLP3_3BIM.ViewModels.LojasViewModel>

@{
    ViewData["Title"] = "Área administrativa";
}

<div class="text-center">

    @foreach(var loja in Model)
    {
        <h3> @loja.Nome </h3>
        <p> <a href="/Lojas/Detalhes/@loja.Id">Detalhes</a></p>

        <form action="../Deletar/@loja.Id">
            <button class="btn btn-danger">Deletar</button>
        </form>
        <hr>
    }

</div>

Views/Lojas/CadastrarLoja.cshtml
@model AvaliacaoLP3_3BIM.ViewModels.LojasViewModel;

@{
    ViewData["Title"] = "Cadastrar Lojas";
}

<div class="text">
    <h1 class="display-4">Cadastrar Loja</h1>
    <hr>
       
</div>
<div class="container">
    <form action="ValidarCadastro" method="POST">
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" name="nome" id="nome" class="form-control" required>
        </div>  
        <div class="form-group">
            <label for="nome">Identificador</label>
            <input type="number" name="id" id="id" class="form-control" required>
        </div> 
        <div class="form-group" >
            <label for="email">Email</label>
            <input type="email" name="email" id="email" class="form-control" required>
        </div> 

        <div class="form-group row">
            <div class="form-group col-md-6">
                <label for="piso">Piso</label>
                <select class="form-control form-control-sm" name="piso" id="piso" required>
                    <option value="" disabled selected>Selecione o piso da loja</option>
                    <option value="1">Piso 1</option>
                    <option value="2">Piso 2</option>
                    <option value="3">Piso 3</option>                        
                </select>
            </div>
                <div class="form-group col-md-6">
                    <label for="piso">Categoria</label>
                    <select class="form-control form-control-sm" name="categoria" id="categoria" required>
                        <option value="" disabled selected> Selecione a categoria da loja</option>
                        <option value="Loja">Loja</option>
                        <option value="Kiosque">Kiosque</option>
                    </select>
            </div>
        
        </div>              

        <div class="form-group">
            <label for="descricao">Descrição</label>
            <textarea class="form-control" name="descricao" id="descricao" cols="30" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>

Views/Lojas/Deletar.cshtml
@{
    ViewData["Title"] = "Sucesso!";
}

<div class="text-center">
    <h1 class="display-4">O comércio foi deletado com sucesso</h1>
</div>

Views/Lojas/Detalhes.cshtml
@model AvaliacaoLP3_3BIM.ViewModels.LojasViewModel;

@{
    ViewData["Title"] = "Detalhes de " + Model.Nome;
}
<div class="text-center">
    <h1 class="display-4">Detalhes</h1>

    <h1>Nome: @Model.Nome</h1>
    <p>Identificador: @Model.Id</p>
    <p>Descrição: @Model.Descricao</p>
    <p>Piso: @Model.Piso</p>
    <p>Tipo: @Model.TipoLoja</p>
    <p>Contato: @Model.Email</p>

    <form action="../Deletar/@Model.Id">
        <button class="btn btn-danger">Deletar</button>
    </form>

</div>

Views/Lojas/Loja.cshtml
@model List<AvaliacaoLP3_3BIM.ViewModels.LojasViewModel>

@{
    ViewData["Title"] = "Loja";
}

<div class="text-center">
    <h1 class="display-4">Bem vinde ao Gucci's Shopping Central</h1>
    <h3 class="display-4">Lojas disponíveis no momento:</h3>

    @if (Model.Count == 0)
    {
        <p>Nenhuma loja cadastrada</p>
        <button> <a href="/Lojas/CadastrarLoja">Cadastrar nova loja</a></button>
    }
    else
    {

        @foreach (var loja in Model)
        {
            <h3>
                <a href="/Lojas/Detalhes/@loja.Id">@loja.Nome</a>
            </h3>
            <p>@loja.Piso</p>
            <p>@loja.TipoLoja</p>
            <hr>
        }

        <button> <a href="/Lojas/CadastrarLoja">Cadastrar nova loja</a></button>
    }
</div>

Views/Lojas/ValidarCadastro.cshtml
@{
    ViewData["Title"] = "Erro";
    var nome = ViewData["nome"];
}
<div class="text-center">
    <h1 class="display-4">Uma loja nomeada de "@nome" já foi cadastrada, por favor selecione outro nome.</h1>
</div>

Views/Lojas/ValidarId.cshtml
@{
    ViewData["Title"] = "Erro";
}
<div class="text-center">
    <h1 class="display-4">Uma loja já foi cadastrada com esse ID, por favor selecione outro.</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvaliacaoLP3_3BIM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AvaliacaoLP3_3BIM.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvaliacaoLP3_3BIM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Loja">Nossas lojas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="CadastrarLoja">Cadastrar loja</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lojas" asp-action="Administracao">Admin</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AvaliacaoLP3_3BIM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>